- name: first play
  hosts: local
  connection: local
  tasks: 
  - name: msg from task1
    ansible.builtin.debug:
      msg: "Hello from task 1 and play 1"
  - name: msg from task2
    ansible.builtin.debug:
      msg: "Hello from task 2 and play 1"
- name: second play
  hosts: local
  connection: local
  tasks: 
  - name: msg from task1
    ansible.builtin.debug:
      msg: "Hello from task 1 and play 2"
  - name: msg from task2
    ansible.builtin.debug:
      msg: "Hello from task 2 and play 2"