- name: varaibles from files
  hosts: local
  connection: local
  vars_files:
  - course_details.yaml
  tasks:
  - name: varaibles from files
    ansible.builtin.debug:
      msg: "hello {{ COURSE }}, Duration: {{ DURATION }}, Trainer: {{ TRAINER }}"