- name: error-handling practise
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: check the user if exists
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true

  - name: create user
    ansible.builtin.command: useradd roboshop
    when: output.rc !=0

  - name: user already exists
    ansible.builtin.debug:
      msg: user already exists
    when: output.rc ==0